# Generated by Django 3.1.7 on 2021-03-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckettype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='bucket type name'),
        ),
    ]
