# Generated by Django 3.1.7 on 2021-03-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '0002_auto_20210325_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='buckets',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='buckets',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='buckets',
            name='name',
            field=models.CharField(max_length=63, null=True, unique=True, verbose_name='bucket name'),
        ),
        migrations.AddField(
            model_name='buckets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buckets',
            name='start_time',
            field=models.IntegerField(default=0, verbose_name='start time'),
        ),
    ]
