# Generated by Django 3.1.7 on 2021-03-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20210325_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buckets',
            name='bucket_type',
        ),
    ]
