# Generated by Django 3.1.7 on 2021-04-01 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_remove_buckets_bucket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketRegion',
            fields=[
                ('reg_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('secret_key', models.CharField(max_length=50, verbose_name='secret key')),
                ('access_key', models.CharField(max_length=50, verbose_name='access key')),
                ('server', models.CharField(max_length=20, verbose_name='server ip')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='buckets',
            name='bucket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buckets.buckettype'),
        ),
        migrations.AddField(
            model_name='buckets',
            name='version_control',
            field=models.BooleanField(default=False, verbose_name='version control'),
        ),
        migrations.AddField(
            model_name='buckets',
            name='bucket_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buckets.bucketregion'),
        ),
    ]
