# Generated by Django 3.1.7 on 2021-04-01 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '0005_auto_20210401_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketacl',
            old_name='acl_id',
            new_name='acl_bid',
        ),
        migrations.RemoveField(
            model_name='bucketacl',
            name='list',
        ),
        migrations.RemoveField(
            model_name='bucketacl',
            name='read',
        ),
        migrations.RemoveField(
            model_name='bucketacl',
            name='write',
        ),
        migrations.AddField(
            model_name='bucketacl',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bucketacl',
            name='permission',
            field=models.CharField(default='private', max_length=50, verbose_name='bucket permission'),
        ),
        migrations.AlterField(
            model_name='bucketacl',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_acl', to='buckets.buckets'),
        ),
        migrations.AlterField(
            model_name='bucketacl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
