# Generated by Django 3.1.7 on 2021-04-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20210401_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buckets',
            name='bucket_type',
        ),
    ]
