# Generated by Django 3.1.7 on 2021-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_remove_buckets_bucket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckets',
            name='bucket_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
