# Generated by Django 3.1.7 on 2021-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0008_auto_20210401_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='buckets',
            name='permission',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
