# Generated by Django 3.1.7 on 2021-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_bucketregion_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckets',
            name='state',
            field=models.CharField(choices=[('e', 'enable'), ('d', 'disable'), ('s', 'suspend')], default='e', max_length=1, verbose_name='state'),
        ),
    ]
