# Generated by Django 3.1.7 on 2021-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_auto_20210427_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketregion',
            name='state',
            field=models.CharField(choices=[('e', 'enable'), ('d', 'disable'), ('s', 'suspend')], default='e', max_length=1, verbose_name='region state'),
        ),
    ]
