# Generated by Django 3.1.7 on 2021-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0012_auto_20210428_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketregion',
            name='state',
            field=models.CharField(choices=[('e', 'enable'), ('d', 'disable')], default='e', max_length=1, verbose_name='region state'),
        ),
    ]
