# Generated by Django 3.1.7 on 2021-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='plan name')),
                ('s_price', models.FloatField(verbose_name='storage price')),
                ('b_price', models.FloatField(verbose_name='bandwidth price')),
                ('state', models.CharField(choices=[('e', 'enable'), ('d', 'disable')], max_length=1)),
                ('offset', models.FloatField(default=1.0, verbose_name='offset')),
                ('min_days', models.IntegerField(blank=True, default=365, verbose_name='offset mini days')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
