# Generated by Django 3.2.2 on 2021-08-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='plan name')),
                ('s_price', models.FloatField(verbose_name='storage price')),
                ('b_price', models.FloatField(verbose_name='bandwidth price')),
                ('state', models.CharField(choices=[('e', 'enable'), ('d', 'disable')], max_length=1)),
                ('offset', models.FloatField(default=1.0, verbose_name='offset')),
                ('offset_min_days', models.IntegerField(blank=True, default=0, verbose_name='offset mini days')),
                ('plan_min_days', models.IntegerField(blank=True, default=0, verbose_name='plan mini days')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='order no.')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('s', 'Storage'), ('b', 'Bandwidth')], max_length=1)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('pay', models.FloatField()),
                ('real_pay', models.FloatField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_plan', to='account.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
