# Generated by Django 3.1.7 on 2021-04-28 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='min_days',
        ),
        migrations.AddField(
            model_name='plan',
            name='offset_min_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='offset mini days'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_min_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='plan mini days'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='order no.')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('s', 'Storage'), ('b', 'Bandwidth')], max_length=1)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('pay', models.FloatField()),
                ('offset', models.FloatField()),
                ('real_pay', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
