# Generated by Django 3.1.7 on 2021-04-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210428_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offset',
        ),
    ]
