# Generated by Django 3.1.7 on 2021-04-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_order_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_plan', to='account.plan'),
        ),
    ]
