stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - oss-server
  script:
     - rm -f db.sqlite3
     - cp -rf * /home/oss/
     - python3 ./manage.py makemigrations
     - python3 ./manage.py migrate
     - systemctl restart oss-web.service
