# Generated by Django 3.2.2 on 2021-08-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buckets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('obj_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='filename')),
                ('type', models.CharField(choices=[('f', 'file'), ('d', 'directory')], max_length=1, verbose_name='file type')),
                ('root', models.CharField(blank=True, max_length=2048, null=True, verbose_name='root path')),
                ('file_size', models.IntegerField(blank=True, default=0, verbose_name='file size')),
                ('md5', models.CharField(blank=True, max_length=50, null=True, verbose_name='upload file md5')),
                ('etag', models.CharField(blank=True, max_length=50, null=True, verbose_name='s3 etag')),
                ('key', models.CharField(blank=True, max_length=4096, null=True, verbose_name='keys')),
                ('version_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='version id')),
                ('permission', models.CharField(default='private', max_length=50)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_bucket', to='buckets.buckets')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bucket', 'owner', 'key', 'version_id')},
            },
        ),
        migrations.CreateModel(
            name='ObjectAcl',
            fields=[
                ('acl_oid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=50, verbose_name='acl name')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_acl', to='objects.objects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
