# Generated by Django 3.1.7 on 2021-03-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='root',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='root path'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
