# Generated by Django 3.1.7 on 2021-03-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20210326_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='version_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='version id'),
        ),
    ]
