# Generated by Django 3.1.7 on 2021-04-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20210328_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='key',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='keys'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='root',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='root path'),
        ),
    ]
