# Generated by Django 3.1.7 on 2021-04-01 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0006_auto_20210401_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAcl',
            fields=[
                ('acl_oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=50, verbose_name='acl name')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
