# Generated by Django 3.1.7 on 2021-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_auto_20210406_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='permission',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
