# Generated by Django 3.2.2 on 2021-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_objects_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectacl',
            name='acl_oid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
