# Generated by Django 3.2.2 on 2021-08-25 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('phone_verify', models.BooleanField(default=False)),
                ('parent_uid', models.CharField(blank=True, max_length=50, verbose_name='sub user parent username')),
                ('root_uid', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='sub user root username')),
                ('level', models.IntegerField(default=0, verbose_name='sub user deep level, max allow 3 leve')),
                ('balance', models.FloatField(default=0.0, verbose_name='user account balance')),
                ('offset', models.FloatField(default=1.0, verbose_name='user offset')),
                ('is_subuser', models.BooleanField(default=False, verbose_name='is sub user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ceph_uid', models.CharField(blank=True, max_length=20, verbose_name='ceph uid')),
                ('ceph_secret_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ceph_access_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('key_type', models.CharField(blank=True, default='s3', max_length=5)),
                ('user_secret_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user_access_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('allow_ip', models.CharField(default='*', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False, verbose_name='whether user default role')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_group', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityQuota',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.IntegerField(default=0, verbose_name='start time')),
                ('capacity', models.IntegerField(default=0, verbose_name='capacity')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('sync', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_capacity_quota',
            },
        ),
        migrations.CreateModel(
            name='BandwidthQuota',
            fields=[
                ('b_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.IntegerField(default=0, verbose_name='start time')),
                ('bandwidth', models.IntegerField(default=4, verbose_name='bandwidth')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bandwidth_quota',
            },
        ),
    ]
