# Generated by Django 3.1.7 on 2021-03-25 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('phone_verify', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=32, verbose_name='ceph access key')),
                ('access_key', models.CharField(blank=True, max_length=32, verbose_name='ceph access secret')),
                ('key_type', models.CharField(blank=True, max_length=5)),
                ('parent_uid', models.CharField(blank=True, max_length=50, verbose_name='parent account username')),
                ('is_subuser', models.BooleanField(default=False, verbose_name='is sub user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='account balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
