# Generated by Django 3.1.7 on 2021-04-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ceph_uid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ceph uid'),
        ),
    ]
