# Generated by Django 3.1.7 on 2021-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_ceph_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='ceph access secret'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='ceph access key'),
        ),
    ]
