# Generated by Django 3.1.7 on 2021-04-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210401_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_key',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ceph access secret'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_uid',
            field=models.CharField(blank=True, max_length=50, verbose_name='sub account parent account username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ceph access key'),
        ),
    ]
