# Generated by Django 3.1.7 on 2021-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210402_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ceph access secret'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ceph access key'),
        ),
    ]
