# Generated by Django 3.1.7 on 2021-04-06 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20210402_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.IntegerField(default=0, verbose_name='start time')),
                ('capacity', models.IntegerField(default=0, verbose_name='capacity')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
