# Generated by Django 3.1.7 on 2021-04-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money', to=settings.AUTH_USER_MODEL),
        ),
    ]
