# Generated by Django 3.1.7 on 2021-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210412_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bandwidth',
            field=models.IntegerField(default=4, max_length=2, verbose_name='user download bandwidth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0, verbose_name='user level, max allow 3 leve'),
        ),
    ]
