# Generated by Django 3.1.7 on 2021-04-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210422_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bandwidth',
            field=models.IntegerField(default=4, verbose_name='user download bandwidth'),
        ),
    ]
