# Generated by Django 3.1.7 on 2021-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210425_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='user account balance'),
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
