# Generated by Django 3.1.7 on 2021-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210429_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthquota',
            name='start_time',
            field=models.IntegerField(default=1619682361, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='capacityquota',
            name='start_time',
            field=models.IntegerField(default=1619682361, verbose_name='start time'),
        ),
    ]
