# Generated by Django 3.1.7 on 2021-04-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210429_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='allow_ip',
            field=models.CharField(default='*', max_length=15),
        ),
        migrations.AlterField(
            model_name='bandwidthquota',
            name='start_time',
            field=models.IntegerField(default=1619745453, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='capacityquota',
            name='start_time',
            field=models.IntegerField(default=1619745453, verbose_name='start time'),
        ),
    ]
