# Generated by Django 3.1.7 on 2021-04-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0022_auto_20210430_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthquota',
            name='start_time',
            field=models.IntegerField(default=1619747830, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='capacityquota',
            name='start_time',
            field=models.IntegerField(default=1619747830, verbose_name='start time'),
        ),
        migrations.CreateModel(
            name='DefaultGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False, verbose_name='whether user default role')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_group', to='auth.group')),
            ],
        ),
    ]
