# Generated by Django 3.2.2 on 2021-05-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210430_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthquota',
            name='start_time',
            field=models.IntegerField(default=1620615696, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='capacityquota',
            name='start_time',
            field=models.IntegerField(default=1620615696, verbose_name='start time'),
        ),
    ]
