# Generated by Django 3.2.2 on 2021-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210510_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthquota',
            name='start_time',
            field=models.IntegerField(default=1622099250, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='capacityquota',
            name='start_time',
            field=models.IntegerField(default=1622099250, verbose_name='start time'),
        ),
    ]
